### ISSUE TITLE
Kinetic Multi-Tool charging issue

### ISSUE THREAD

**Issue by Be-Cool-Man** [BCA-Team/Buildcraft-Additions#308] opened 2015-03-05 21:19 UTC
If you put thre empty Kinetic Capsules (must be the same tier) in the Kinetic Multi-Tool and put it in the Charging Station, the third Capsule gets an "endless" amount of energy (e.g: 1051324296 / 100000 RF) Mixed tiers working as provided.

€dith:
If i put the Energy Capsule after charging into the Charging Table (from BC) the right tab shows the following:
Enegy Required: -1051224296 RF
Stored: -1 RF
Energy Rate: 0,0 RF/t

If you compare the two numbers, then a difference of 100000 RF is to determine (if you ignore the minus sign)

**Comment by iTitus** [comment] 2015-03-05 21:24
Thats... strange.

**Comment by iTitus** [comment] 2015-03-06 15:09
Can't reproduce...

**Comment by AEnterprise** [comment] 2015-03-06 18:44
@Be-Cool-Man can you provide a modlist with version numbers?

**Comment by iTitus** [comment] 2015-03-06 21:04
@Be-Cool-Man This will be fixed in 2.1.0

**Comment by Be-Cool-Man** [comment] 2015-03-06 21:41
Sorry for late respone.

Here is the list:

[1.7.10]Treecapitator-universal-2.0.4
appliedenergistics2-rv2-beta-8
bamsgrave-1.7.2-1.4.2_01
buildcraft-6.4.2
BuildcraftAdditions-1.7.10-2.0.2
buildcraft-compat-6.4.0
ChickenChunks-1.7.10-1.3.4.17-universal
CodeChickenCore-1.7.10-1.0.4.35-universal (1)
EnderIO-1.7.10-2.2.8.344
EnderStorage-1.7.10-1.4.5.27-universal
extrautilities-1.2.1
ForgeMultipart-1.7.10-1.1.1.321-universal
neiaddons-mc1710-1.12.3.11
NEIIntegration-MC1.7.10-1.0.6
NotEnoughItems-1.7.10-1.0.4.83-universal
OpenEye-0.6-1.7.10
QuarryPlus-1.7.10-2.0.3
simplefluidtanks-1.7.10-1.2.0.5
Telepads-1.7.2_1.7
Waila-1.5.8a_1.7.10

**Comment by AEnterprise** [comment] 2015-03-07 10:28
@Be-Cool-Man yes this is a BCA issue but has been fixed on the development branch, sadly the branch isn't ready for release yet

**Comment by Speiger** [comment] 2015-03-07 11:01
For me it sounds like a Sync Problem between Server and Client. In terms that you believed that the Container sends the server data as Integer, but it sends it as Short...

**Comment by AEnterprise** [comment] 2015-03-07 11:07
@Speiger the tool has been re-written and both iTitus and big_Xplosion tried it and where unable to reproduce this

**Comment by Be-Cool-Man** [comment] 2015-03-07 11:18
@AEnterprise 
Don't haste. I can wait.

**Comment by Speiger** [comment] 2015-03-07 23:46
@AEnterprise i think you guys are only testing on client only right? There you do not have these sync issus because the Server there do not send packets to the client (and even if they get handled totally differend then in servers), so every ContainerData Sending that happends through the ICrafting value will be requesting a Integer but is limited to a short.... So if you send more then a Short.Max_Value (32565) then it will be turned into a will be ending with a completly differend number

**Comment by AEnterprise** [comment] 2015-03-08 10:44
@Speiger we mostly test on the client but i test some things on the server as well from time to time but i don't test everything and all corner cases again, that is just to time consuming

**Comment by AEnterprise** [comment] 2015-03-16 10:54
someone claims this is still an issue in one of the recent jenkins builds

@iTitus can you test this again on a server please to be sure?

**Comment by iTitus** [comment] 2015-03-16 12:44
Will test now

**Comment by iTitus** [comment] 2015-03-19 15:48
Couldn't reproduce

**Closed** 2015-03-19 15:52 UTC
