### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Xen1290** [BCA-Team/Buildcraft-Additions#441] opened 2015-07-06 12:06 UTC
Hi, other error in console, BCA 2.2.0 Forge 1481
[14:03:50] [Client thread/INFO] [BuildCraft Additions]: Buildcraft refinery recipe detected, input: Oil, output: Fuel
[14:03:50] [Client thread/WARN] [FML]: ****************************************
[14:03:50] [Client thread/WARN] [FML]: * The object buildcraftAdditions.items.ItemBucketBCA@b1349ff has been registered twice for the same name bcadditions:bioethanolgasBucket.
[14:03:50] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:376)
[14:03:50] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:845)
[14:03:50] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:808)
[14:03:50] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:149)
[14:03:50] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:137)
[14:03:50] [Client thread/WARN] [FML]: * at buildcraftAdditions.utils.fluids.RefineryRecipeConverter.doYourThing(RefineryRecipeConverter.java:78)...
[14:03:50] [Client thread/WARN] [FML]: ****************************************
[14:03:50] [Client thread/WARN] [FML]: ****************************************
[14:03:50] [Client thread/WARN] [FML]: * The object buildcraftAdditions.items.ItemBucketBCA@3c1d66df has been registered twice for the same name bcadditions:fuelgasBucket.
[14:03:50] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:376)
[14:03:50] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:845)
[14:03:50] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:808)
[14:03:50] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:149)
[14:03:50] [Client thread/WARN] [FML]: * at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:137)
[14:03:50] [Client thread/WARN] [FML]: * at buildcraftAdditions.utils.fluids.RefineryRecipeConverter.doYourThing(RefineryRecipeConverter.java:78)...
[14:03:50] [Client thread/WARN] [FML]: ****************************************

**Comment by Adaptivity** [comment] 2015-07-07 14:31
Can confirm

**Comment by AEnterprise** [comment] 2015-07-07 14:33
duplicate of #439 , different thing, same cause

**Closed by AEnterprise** 2015-07-07 14:33 UTC
