### ISSUE TITLE
[QUESTION] Coolant tower does not import fuel gas?

### ISSUE THREAD

**Issue by hron84** [BCA-Team/Buildcraft-Additions#459] opened 2015-12-21 01:54 UTC
I trying to use BCA 2.2.3 with BC 7.1.14 and BC-Compat 7.1.3. I built a Coolant Tower, it formed right, I feeding it with water and I trying to feed it with a Fuel Gas right from my BCA Refinery. However, I see the bottom valve is filled with Fuel Gas but it does not show up in the coolant tower GUI, it stays empty. Did I something wrong? Or how can I fill the internal tank of the Coolant Tower with Gas

**Comment by hron84** [comment] 2015-12-21 02:16
**Update:** I installed Auto-Import and Auto-Export upgrades on respective Coolant Tower Valves, and now it seems like to import the Fuel Gas, and **visually** outputs Fuel. However, this fuel is a ghost liquid as I cannot extract it from any liquid container. I do not know how it happens, but I tried with BC tanks and also EIO Fluid Tanks, and the WAILA shows the contained liquid, but no pipe can extract it from the tank. This liquid seems non-existent from some aspect. Really weird.

**Comment by iTitus** [comment] 2015-12-21 06:05
Hmm, that is really weird.

**Comment by AEnterprise** [comment] 2015-12-21 09:13
hmm, might be a desync then? i'll take a look into reproducing it

**Comment by AEnterprise** [comment] 2015-12-21 10:52
cannot reproduce, seems this is eighter another mod messing with it or a user error
![2015-12-21_11 45 20](https://cloud.githubusercontent.com/assets/5206666/11929157/086ea24c-a7d9-11e5-8f92-9bb98c12a2e5.png)

**Comment by hron84** [comment] 2015-12-21 18:47
@AEnterprise I see it in SSP, and I'm pretty disappointed. I saw a video about how it works, so I basically went step-by-step based on that, and the refinery worked fine, but coolant tower is not. So, refinery took the power, imported oil and produced the fuel gas. However, Coolant tower without a auto import/export module did not do anything, even if both valves displayed the info 2000 mB Fuel Gas included. After I installed these modules, it could import the gas from tanks (from pipes still not), I mean then the fuel gas is started to displaying in the gui. After that, I saw a vibrating numbers between 1 and maybe 30? (it started count to 30 but always reset at some point) on the output tank display, So, the cooled fuel did not stacked in the output tank and thus I weren't able to extract it on any way (nor BC pipes, nor EIO pipes nor EIO tanks with pull mode were able to extract). The only way I were to able export was the auto-export module, it started to export only to tanks (still not to pipes) but the exported fluid disappeared when I tried to get it somehow. I saw a fluid meter, but I could not extract any real fluid, nor with a bucket, nor with a pipe, nor with any other way. Coolant Tower seems does not like any pipe. 

I can provide a mod list if you want, but basically I use BC, BC-Compat, BCA (now disabled), AdditionalPipesBC and LogisticsPipes that could be related to BC-issues.

**Comment by AEnterprise** [comment] 2015-12-21 19:55
so you mean things are going wrong on a server? (asking to be sure)

i tried pipes (regular BC pipes not sure what you're using) and it worked fine without any auto-import/export. can you reproduce this with just the min needed mods (BC + BCA)? and why did you dissable BCA? just cause the refinery doesn't fully work you don't need to take out an entire mod

**Comment by hron84** [comment] 2015-12-22 06:56
@AEnterprise I do not say anything about servers or clients, since - again - I play in single player (SSP not SMP). I dunno what happened.

I disabled it because it was the easiest way to remove coolant tower since it crashed the game when I tried to dismantle it. And I did not used any other important block from it yet. Also, the multiblock refinery was one of the reason why I installed this mod :-( Sorry, it was purely a decision based on impressions. 

I will try it out, but not today or tomorrow. Maybe tomorrow, but I'm not sure in it. I've a busy time now.

**Comment by hron84** [comment] 2015-12-22 06:59
@AEnterprise if it will work as standalone, could you help me after try to figure out which mod can cause the issue? I wouldn't like to be left alone after we reveal some mod messes up the stuff...

**Comment by AEnterprise** [comment] 2015-12-22 07:12
alright so it works in single player for me and standalone for you, i sugest you add in the mods again one by one till you find the cullpit, then we can see if there's something that can be done from my end about it

**Comment by AEnterprise** [comment] 2016-01-24 09:56
closing as i can't reproduce and didn't get any new info on how to reproduce

if someone can provide steps for me to reproduce i'll re-open and investigate further

**Closed by AEnterprise** 2016-01-24 09:56 UTC
Labels: investigate
