### ISSUE TITLE
Crashed to desktop trying to open a KEB

### ISSUE THREAD

**Issue by misterfixit** [BCA-Team/Buildcraft-Additions#405] opened 2015-05-09 00:38 UTC
https://www.dropbox.com/s/e99x4irppwwgsw5/crash-2015-05-08_20.36.04-client.txt?dl=0

**Comment by AEnterprise** [comment] 2015-05-09 07:58
should be an easy fix

**Comment by AEnterprise** [comment] 2015-05-09 15:45
hmm, seems like the only thing that would cause this crash is an KEB with a capacity of 0, that would probably be caused by a setting in your configs or something messed with the keb NBT data

**Comment by AEnterprise** [comment] 2015-05-13 09:26
@misterfixit any update on this?

**Comment by misterfixit** [comment] 2015-05-14 03:29
I haven't run into the issue recently but the KEB defenitely did not have a capacity of 0

**Comment by AEnterprise** [comment] 2015-05-15 08:23
does it still heapen or was this a one time occurance?

**Comment by AEnterprise** [comment] 2015-05-15 18:21
found the bug

**Comment by AEnterprise** [comment] 2015-05-15 18:37
should be fixed

**Closed by AEnterprise** 2015-05-15 18:37 UTC
Labels: bug

**Comment by misterfixit** [comment] 2015-05-16 22:25
thanks sorry I couldnt be of much help it was very random it seemed
