### ISSUE TITLE
buildcraftAdditions/compat/buildcraft/recipe/ToolCoreRecipe

### ISSUE THREAD

**Issue by Sasikaa** [BCA-Team/Buildcraft-Additions#411] opened 2015-05-11 06:58 UTC
Here is my crash log with new BC7.0.4 and BC-C 7.0.2:

---- Minecraft Crash Report ----
// Don't do that.

Time: 5/11/15 8:54 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraftAdditions/compat/buildcraft/recipe/ToolCoreRecipe
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:299)
	at com.creativemd.minecraftloader.ClientHelper.startGame(ClientHelper.java:307)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: buildcraftAdditions/compat/buildcraft/recipe/ToolCoreRecipe
	at buildcraftAdditions.reference.ItemsAndBlocks.addRecipes(ItemsAndBlocks.java:405)
	at buildcraftAdditions.BuildcraftAdditions.load(BuildcraftAdditions.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:530)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.callMethod(MinecraftDummyContainer.java:209)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.onModEvent(MinecraftDummyContainer.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
	... 19 more
Caused by: java.lang.ClassNotFoundException: buildcraftAdditions.compat.buildcraft.recipe.ToolCoreRecipe
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 52 more
Caused by: java.lang.NoClassDefFoundError: buildcraft/silicon/recipes/IntegrationTableRecipe
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 54 more
Caused by: java.lang.ClassNotFoundException: buildcraft.silicon.recipes.IntegrationTableRecipe
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 58 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 293168320 bytes (279 MB) / 794058752 bytes (757 MB) up to 4207738880 bytes (4012 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - MAtmos version r28 for 1.7.10
	LaunchWrapper: 41 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: me.guichaguri.betterfps.BetterFpsTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: com.creativemd.minecraftloader.MinecraftTransformer
          - Transformer: mcp.mobius.mobiuscore.asm.CoreTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: redgear.core.asm.GlassAndIceTransformer
          - Transformer: redgear.core.asm.FiniteWaterTransformer
          - Transformer: redgear.core.asm.SafeCactusTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: aroma1997.core.coremod.asm.AromaAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: mcp.mobius.mobiuscore.asm.CoreAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: tterrag.core.common.transform.TTCoreTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
          - Transformer: mods.immibis.core.impl.MultiInterfaceClassTransformer
          - Transformer: mods.immibis.core.impl.TraitTransformer
	JVM Flags: 14 total; -XX:+UseLargePages -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+UseBiasedLocking -Xincgc -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:+CMSParallelRemarkEnabled -XX:ParallelGCThreads=10 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m -XX:PermSize=512m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1388 82 mods loaded, 82 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{7.10.114.1388} [Forge Mod Loader] (forge-1.7.10-10.13.3.1388-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{10.13.3.1388} [Minecraft Forge] (forge-1.7.10-10.13.3.1388-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized
	betterfps{1.0.0} [BetterFps] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	minecraftloader{0.1} [MinecraftLoader] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NotEnoughItems{1.0.4.106} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.106-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	debug{1.0} [debug] (denseores-1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	IC2{2.2.718-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.718-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ImmibisCore{59.0.8} [Immibis Core] (immibis-core-59.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
	AdvancedMachines{59.0.2} [Advanced Machines] (advanced-machines-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized
	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
	bdlib{1.7.1.71} [BD Lib] (bdlib-mc1710-1.7.1.71.jar) Unloaded->Constructed->Pre-initialized->Initialized
	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.104-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	bluepower{0.2.938} [Blue Power] (BluePower-1.7.10-0.2.938-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-273.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Core{7.0.4} [BuildCraft] (buildcraft-7.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Silicon{7.0.4} [BC Silicon] (buildcraft-7.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Factory{7.0.4} [BC Factory] (buildcraft-7.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Builders{7.0.4} [BC Builders] (buildcraft-7.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Energy{7.0.4} [BC Energy] (buildcraft-7.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Robotics{7.0.4} [BC Robotics] (buildcraft-7.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Transport{7.0.4} [BC Transport] (buildcraft-7.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BuildCraft|Compat{7.0.2} [BuildCraft Compat] (buildcraft-compat-7.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	bcadditions{2.1.3} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Errored
	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed->Pre-initialized->Initialized
	DimensionalAnchors{59.0.2} [Dimensional Anchors] (dimensional-anchor-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	EnderStorage{1.4.7.33} [EnderStorage] (EnderStorage-1.7.10-1.4.7.33-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ExtrabiomesXL{3.16.2} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forestry{3.5.4.13} [Forestry for Minecraft] (forestry_1.7.10-3.5.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized
	advgenerators{0.9.12.64} [Advanced Generators] (generators-mc1710-0.9.12.64.jar) Unloaded->Constructed->Pre-initialized->Initialized
	IC2NuclearControl{2.2.1a-Yolo} [Nuclear Control 2] (IC2NuclearControl-2.2.1a-Yolo.jar) Unloaded->Constructed->Pre-initialized->Initialized
	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) Unloaded->Constructed->Pre-initialized->Initialized
	iridiummod{0.8} [Iridium Mod] (iridiummod-1.7-0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	RadixCore{2.0.1} [RadixCore] (RadixCore-2.0.1-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	MCA{5.0.3} [Minecraft Comes Alive] (MCA-5.0.3-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	redgear_core{2.1.3} [Red Gear Core] (RedGearCore-1.7.10-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	redgear_morebackpacks{2.2.2} [More Backpacks] (More Backpacks-1.7.10-2.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons{1.12.7.21} [NEI Addons] (neiaddons-mc1710-1.12.7.21.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|AppEng{1.12.7.21} [NEI Addons: Applied Energistics 2] (neiaddons-mc1710-1.12.7.21.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|Botany{1.12.7.21} [NEI Addons: Botany] (neiaddons-mc1710-1.12.7.21.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|Forestry{1.12.7.21} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.7.21.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|CraftingTables{1.12.7.21} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.7.21.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NEIAddons|ExNihilo{1.12.7.21} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.7.21.jar) Unloaded->Constructed->Pre-initialized->Initialized
	neiintegration{1.0.7} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NotEnoughCodecs{0.3} [NotEnoughCodecs] (NotEnoughCodecs-1.7.10-0.3-snapshot-11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) Unloaded->Constructed->Pre-initialized->Initialized
	neresources{0.1.0.95} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.95.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	PowerConverters{1.7.10_3.2.0-jenkins.61} [Power Converters] (PowerConverters-1.7.10_3.2.0-jenkins.61.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ProjectE{1.7.10-PE1.4.5} [ProjectE] (ProjectE-1.7.10-PE1.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ReiMinimap{1.7.10} [Rei's Minimap] (ReiMinimap-1.7.10-3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	screwdriver{2.0} [Hlestakov's Screwdriver] (screwdriver-2.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	StorageDrawers{1.7.10-1.3.9} [Storage Drawers] (StorageDrawers-1.7.10-1.3.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ttCore{MC1.7.10-0.1.0-67} [ttCore] (ttCore-MC1.7.10-0.1.0-67.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Tubestuff{59.0.3} [Tubestuff] (tubestuff-59.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	wailaplugins{MC1.7.10-0.0.1-14} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.0.1-14.jar) Unloaded->Constructed->Pre-initialized->Initialized
	wawla{1.2.1} [What Are We Looking At] (Wawla-1.2.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ForgeMultipart{1.1.2.332} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.332-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	McMultipart{1.1.2.332} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.332-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	aobd{2.6.0} [Another One Bites The Dust] (AOBD-2.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ForgeMicroblock{1.1.2.332} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.332-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CoFHCore: -[1.7.10]3.0.2-273
	NetherOres: -[1.7.10]2.3.0-12
	List of loaded APIs: 
		* API_NEK (1.0.0) from NotEnoughKeys-1.7.10-1.0.0b29.jar
		* appliedenergistics2|API (rv1) from screwdriver-2.2.3.jar
		* bcadditionsAPI (2.1.1) from BuildcraftAdditions-1.7.10-2.1.3.jar
		* bluepowerAPI (1.0) from BluePower-1.7.10-0.2.938-universal.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.0.4.jar
		* BuildCraftAPI|blueprints (1.2) from buildcraft-7.0.4.jar
		* BuildCraftAPI|boards (1.0) from buildcraft-7.0.4.jar
		* BuildCraftAPI|core (1.0) from screwdriver-2.2.3.jar
		* BuildCraftAPI|events (1.0) from buildcraft-7.0.4.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.0.4.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.0.4.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.0.4.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.0.4.jar
		* BuildCraftAPI|items (1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|library (1.0) from buildcraft-7.0.4.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.0.4.jar
		* BuildCraftAPI|recipes (2.1) from buildcraft-7.0.4.jar
		* BuildCraftAPI|robotics (1.2) from buildcraft-7.0.4.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.0.4.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.0.4.jar
		* BuildCraftAPI|tiles (1.1) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|tools (1.0) from screwdriver-2.2.3.jar
		* BuildCraftAPI|transport (4.0) from Railcraft_1.7.10-9.6.1.0.jar
		* CoFHAPI (1.7.10R1.0.2) from forestry_1.7.10-3.5.4.13.jar
		* CoFHAPI|block (1.7.10R1.0.1) from screwdriver-2.2.3.jar
		* CoFHAPI|core (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHAPI|energy (1.7.10R1.0.1) from BuildcraftAdditions-1.7.10-2.1.3.jar
		* CoFHAPI|fluid (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHAPI|inventory (1.7.10R1.0.1) from buildcraft-compat-7.0.2.jar
		* CoFHAPI|item (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHAPI|tileentity (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHAPI|transport (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHAPI|world (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHLib (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHLib|audio (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHLib|gui (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHLib|gui|container (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHLib|gui|element (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHLib|gui|slot (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHLib|inventory (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHLib|render (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHLib|render|particle (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHLib|util (1.7.10R1.0.0B6) from screwdriver-2.2.3.jar
		* CoFHLib|util|helpers (1.7.10R1.0.0B6) from screwdriver-2.2.3.jar
		* CoFHLib|util|position (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHLib|world (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-273.jar
		* CoFHLib|world|feature (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-273.jar
		* ComputerCraft|API (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|FileSystem (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Lua (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Media (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Peripheral (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Redstone (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Turtle (1.73) from ComputerCraft1.73.jar
		* EnderIOAPI (0.0.1) from screwdriver-2.2.3.jar
		* EnderIOAPI|Tools (0.0.1) from screwdriver-2.2.3.jar
		* ForestryAPI|apiculture (2.6.0) from forestry_1.7.10-3.5.4.13.jar
		* ForestryAPI|arboriculture (2.3.0) from forestry_1.7.10-3.5.4.13.jar
		* ForestryAPI|circuits (1.1.0) from forestry_1.7.10-3.5.4.13.jar
		* ForestryAPI|core (2.6.1) from forestry_1.7.10-3.5.4.13.jar
		* ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.5.4.13.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-3.5.4.13.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-3.5.4.13.jar
		* ForestryAPI|genetics (2.7.0) from forestry_1.7.10-3.5.4.13.jar
		* ForestryAPI|hives (4.0.0) from forestry_1.7.10-3.5.4.13.jar
		* ForestryAPI|lepidopterology (1.1) from forestry_1.7.10-3.5.4.13.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.5.4.13.jar
		* ForestryAPI|recipes (2.1.0) from forestry_1.7.10-3.5.4.13.jar
		* ForestryAPI|storage (2.3.0) from forestry_1.7.10-3.5.4.13.jar
		* ForestryAPI|world (1.1.0) from forestry_1.7.10-3.5.4.13.jar
		* IC2API (1.0) from industrialcraft-2-2.2.718-experimental.jar
		* neresources|API (1.0) from NotEnoughResources-1.7.10-0.1.0.95.jar
		* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.2.1a-Yolo.jar
		* ProjectEAPI (2) from ProjectE-1.7.10-PE1.4.5.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|carts (1.3.1) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|core (1.0) from screwdriver-2.2.3.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|signals (1.3.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.6.1.0.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Forestry : Info: The following plugins have been disabled in the config: propolis.pipe

**Comment by AEnterprise** [comment] 2015-05-11 08:38
hmm, asie told me stuff like this wouldn't change anymore, will need to have a talk to him about this

**Comment by AEnterprise** [comment] 2015-05-11 08:39
duplicate of #410

**Closed by AEnterprise** 2015-05-11 08:39 UTC
