### ISSUE TITLE
fuelgas bioethanolgas went missing

### ISSUE THREAD

**Issue by TheMrCaveman** [BCA-Team/Buildcraft-Additions#392] opened 2015-04-20 19:43 UTC
fuel and bioethanol went missing after upgrading from 2.1.1 to 2.1.2
http://i.imgur.com/2GnYW3U.png

refinery is also not taking oil anymore?

**Comment by AEnterprise** [comment] 2015-04-21 07:43
hmm, did you update your forge?

**Comment by TheMrCaveman** [comment] 2015-04-21 15:45
yes tried everything from 1370 en up

**Comment by AEnterprise** [comment] 2015-04-21 16:06
take a backup and ignore, probably caused by the forge fluid changes

**Comment by AEnterprise** [comment] 2015-04-24 15:26
@TheMrCaveman : is this fixed now?

**Comment by TheMrCaveman** [comment] 2015-04-24 18:57
No it is still missing when upgrading. So refinery is not working anymore. 
It's not taking oil anymore. And all the fuel and bioethanol is simply not there anymore.
Only if i use forge 1343 or below the issue is not happening.

**Comment by iTitus** [comment] 2015-04-24 21:15
Maybe the fluid registration happens "too late" for Forge?

**Comment by iTitus** [comment] 2015-04-24 21:16
Any warnings about that in the console?

**Comment by AEnterprise** [comment] 2015-04-29 12:47
works fine on my end, check the configs to make sure the multiblock refinery is enabled

**Closed by AEnterprise** 2015-04-29 12:47 UTC
Labels: investigate

**Comment by TheMrCaveman** [comment] 2015-05-02 07:48
http://pastebin.com/kzmBvPiQ my server boot console and yes that is enabled!

Still not working here

**Comment by iTitus** [comment] 2015-05-02 09:00
I see some warnings about BCA trying to register null-fluids.
We have added a null-check to the registration, not much we can do else.
I blame Cauldron :P

**Comment by TheMrCaveman** [comment] 2015-05-02 09:38
Well here is a forge only boot:  http://pastebin.com/EQVLvr9x

And this is after confirming:  http://pastebin.com/9sb08vSN

Still not working

**Comment by iTitus** [comment] 2015-05-02 12:07
Maybe BCA 2.1.3 will fix this. But this version is only compatible with BC7
